# Generated by Django 3.2.5 on 2021-07-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('peso', models.TextField(verbose_name='Peso')),
                ('raza', models.TextField(default='Vaca', verbose_name='Raza')),
                ('sexo', models.TextField(verbose_name='Sexo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
